version: '2'
services:

  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR}:/var/www/html
    depends_on:
      - wordpress
    restart: always

  nginxproxy:
    image: nginx:${NGINX_VERSION}
    container_name: nginxproxy
    ports:
      - '80:80'
    volumes:
      - ${NGINXPROXY_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINXPROXY_LOG_DIR}:/var/log/nginx
    depends_on:
      - nginx
    restart: always
