version: '2'
services:

  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR}:/var/www/html
    depends_on:
      - wordpress
    restart: always

  wordpress-lp1:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wordpress-lp1
    volumes:
      - ./wordpress-lp1:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wakeboarder_co_1
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    restart: always

  nginx-lp1:
    image: nginx:${NGINX_VERSION}
    container_name: nginx-lp1
    volumes:
      - ./nginx-lp1:/etc/nginx/conf.d
      - ./logs/nginx-lp1:/var/log/nginx
      - ./wordpress-lp1:/var/www/html
    depends_on:
      - wordpress-lp1
    restart: always

  wordpress-glury:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wordpress-glury
    volumes:
      - ./wordpress-glury:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wordpress-glury
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    restart: always

  nginx-glury:
    image: nginx:${NGINX_VERSION}
    container_name: nginx-glury
    volumes:
      - ./nginx-glury:/etc/nginx/conf.d
      - ./logs/nginx-glury:/var/log/nginx
      - ./wordpress-glury:/var/www/html
    depends_on:
      - wordpress-glury
    restart: always

  nginxproxy:
    image: nginx:${NGINX_VERSION}
    container_name: nginxproxy
    ports:
      - '80:80'
    volumes:
      - ${NGINXPROXY_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINXPROXY_LOG_DIR}:/var/log/nginx
    depends_on:
      - nginx
    restart: always
